version: '3'

services:
  fhir:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 3000
      MONGO_HOSTNAME: mongo
      MONGO_DB_NAME: fhir
      MONGO_PORT: 27017
      RESOURCE_SERVER: http://localhost:3000/
      AUTH_SERVER_URI: http://myauthzserver.com
      CLIENT_ID: client
      CLIENT_SECRET: secret
      AUTH_CONFIGURATION_URI: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_wrEVOihnT/.well-known/openid-configuration
      AUTH_JWKS_URL: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_wrEVOihnT/.well-known/jwks.json
      AUTH_ISSUER: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_wrEVOihnT
      AUTH_ENABLED:
    ports:
      - '3000:3000'
    volumes:
      - ./src:/srv/src
      - ./package.json:/srv/src/package.json
    command: yarn nodemon

  mongo:
    image: mongo:4.0.0
    command: mongod --port 27017
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  mongoclient:
    image: imranq2/mongoclient-aws:0.1.1
    ports:
      - '3010:3000'
    environment:
      MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://mongo:27017

volumes:
  mongo_data:
