name: Docker to AWS ECR

on:
  release:
    types: [created]

env:
  IMAGE_NAME: graphql-fhir
  REPOSITORY_URL: 875300655693.dkr.ecr.us-east-1.amazonaws.com

jobs:
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@master

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_DEPLOYMENT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_DEPLOYMENT_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.previoustag.outputs.tag }}
          GIT_TAG_VERSION: ${{ steps.previoustag.outputs.tag }}
        run: |
          echo ECR_REGISTRY=$ECR_REGISTRY
          echo IMAGE_TAG=$IMAGE_TAG
          echo GIT_TAG_VERSION=$GIT_TAG_VERSION
          echo "GIT Version:"
          which git 
          docker build -t $REPOSITORY_URL/$IMAGE_NAME:$IMAGE_TAG \
            --build-arg GIT_TAG_VERSION=$GIT_TAG_VERSION \
            --build-arg BUILD_ENV=build \
             -f Dockerfile .
          docker push $REPOSITORY_URL/$IMAGE_NAME:$IMAGE_TAG
